import { PortfolioData, Project, Skill } from "@/models/portfolio";

export const getPortfolioData = (): PortfolioData => {
    const projects: Project[] = [
        {
            id: "8",
            title: "Career Development System",
            description: "Career Development System is a web-based platform designed to help schools manage, monitor, and support student career growth and academic progress. The system includes role-based access for Super Admins, Admins, Teachers, and Students to ensure organized and secure management of information and activities. The platform helps improve communication, monitoring, reporting, and overall career development management within the institution.",
            image: "/myprojects/cd0.jpg",
            images: ["/myprojects/cd0.jpg", "/myprojects/cd1.jpg", "/myprojects/cd2.jpg", "/myprojects/cd3.jpg", "/myprojects/cd4.jpg", "/myprojects/cd5.jpg"],
            tags: ["MVC", "PHP", "HTML", "CSS", "MySQL", "JavaScript", "Bootstrap"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Team (4)",
        },
        {
            id: "5",
            title: "SIPAPP Online",
            description: "SIPAPP Online is a web-based system that helps students find and manage their On-the-Job Training (OJT). It allows students to browse partner companies, apply for internships, record daily time logs, submit journals, and track their internship requirements in one platform for easier monitoring and coordination with the University of Rizal System.",
            image: "/myprojects/sipapp0.png",
            images: ["/myprojects/sipapp0.png", "/myprojects/sipapp1.png", "/myprojects/sipapp2.png", "/myprojects/sipapp3.png", "/myprojects/sipapp4.png"],
            tags: ["MVC", "JavaScript", "PHP", "CSS", "MySQL", "HTML"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Solo",
        },
        {
            id: "4",
            title: "Angono Medical Information System",
            description: "Angono Medical Information System is a digital platform designed to manage patient laboratory records and test results efficiently. It allows authorized users such as Medical Technologists, Pathologists, and Doctors to record, update, print, and manage patient information and laboratory test data.",
            image: "/myprojects/amh1.png",
            images: ["/myprojects/amh1.png", "/myprojects/amh2.0.png", "/myprojects/amh2.1.png", "/myprojects/amh3.png", "/myprojects/amh4.png", "/myprojects/amh5.png"],
            tags: ["PHP", "MySQL", "JavaScript", "Bootstrap"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Team (2)",
        },
        {
            id: "2",
            title: "SmartLesson AI",
            description: "A simple yet powerful platform that uses AI to design structured lesson plans with objectives, pacing, and differentiated activities.",
            image: "/myprojects/smartlesson1.png",
            images: ["/myprojects/smartlesson1.png", "/myprojects/smartlesson2.png", "/myprojects/smartlesson3.png", "/myprojects/smartlesson4.png"],
            tags: ["PHP", "CSS3", "JavaScript", "OpenAI", "n8n", "MySQL"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Solo",
        },
        {
            id: "1",
            title: "MyTeacher LMS",
            description: "MyTeacher LMS is a personal learning management system designed for teachers to manage lessons, attendance, tasks, and student records in one place. It allows teachers to upload lesson materials, track student attendance per section, and organize daily teaching activities efficiently.",
            image: "/myprojects/plms1.png",
            images: ["/myprojects/plms1.png", "/myprojects/plms2.png", "/myprojects/plms3.png", "/myprojects/plms4.png"],
            tags: ["PHP", "MySQL", "JavaScript", "HTML5", "CSS3"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Solo",
        },
        {
            id: "3",
            title: "FitQuest Hub",
            description: "Your central fitness dashboard for workouts, nutrition, progress, and personalized goals.",
            image: "/myprojects/fitquest1.png",
            images: ["/myprojects/fitquest1.png", "/myprojects/fitquest2.png", "/myprojects/fitquest3.png", "/myprojects/fitquest4.png"],
            tags: ["Next.js", "TypeScript", "Tailwind CSS", "MySQL"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Solo",
        },
        {
            id: "6",
            title: "SineguAlerts Mobile",
            description: "SineguAlerts Mobile is a mobile application version of an existing web-based trading platform designed to automatically execute trades using multiple trading strategies. The platform serves as an investment tool for generating passive income, especially for users who have little to no knowledge of trading. It provides a more accessible and user-friendly mobile experience while maintaining the core features of the original platform. However, like all investments and trading activities, it also involves financial risks.",
            image: "/myprojects/sinegu1.jpg",
            images: ["/myprojects/sinegu1.jpg", "/myprojects/sinegu2.jpg", "/myprojects/sinegu3.jpg", "/myprojects/sinegu4.jpg", "/myprojects/sinegu5.jpg"],
            tags: ["Flutter", "Laravel", "MySQL", "APK"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Team (2)",
        },
        {
            id: "7",
            title: "Perfecto Ave. Salon Management Mobile",
            description: "Perfecto Ave. Salon Management is a comprehensive Salon Management System designed to efficiently manage salon operations, including appointments and sessions, services, product inventory, point-of-sale (POS) transactions, and business analytics. The system helps streamline daily processes, improve customer service, and provide organized monitoring of salon performance and sales.",
            image: "/myprojects/salon1.jpg",
            images: ["/myprojects/salon1.jpg", "/myprojects/salon2.jpg", "/myprojects/salon3.jpg", "/myprojects/salon4.jpg", "/myprojects/salon5.jpg"],
            tags: ["Flutter", "Laravel", "MySQL", "APK"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Team (2)",
        },
        {
            id: "9",
            title: "Leon Portfolio",
            description: "A modern, high-performance portfolio website designed to showcase professional engineering work. Built with Next.js and Tailwind CSS, it features dynamic animations, smooth transitions, and a premium aesthetic to provide an engaging user experience. The platform highlights various full-stack projects, technical skills, and professional achievements with a focus on clean code and performance.",
            image: "/myprojects/prtfl1.png",
            images: ["/myprojects/prtfl1.png", "/myprojects/prtfl2.png", "/myprojects/prtfl3.png", "/myprojects/prtfl3.1.png", "/myprojects/prtfl4.png", "/myprojects/prtfl5.png"],
            tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "Lucide React"],
            githubUrl: "https://github.com",
            liveUrl: "https://example.com",
            projectType: "Solo",
        },
    ];

    const skills: Skill[] = [
        { name: "HTML5", category: "Frontend", icon: "html5" },
        { name: "CSS3", category: "Frontend", icon: "css3" },
        { name: "JavaScript", category: "Frontend", icon: "javascript" },
        { name: "React", category: "Frontend", icon: "react" },
        { name: "Laravel", category: "Backend", icon: "laravel" },
        { name: "Python", category: "Backend", icon: "python" },
        { name: "MySQL", category: "Database", icon: "mysql" },
        { name: "Git", category: "DevOps", icon: "git" },
        { name: "Flutter", category: "DevOps", icon: "flutter" },
        { name: "Java", category: "DevOps", icon: "java" },
        { name: "PHP", category: "Backend", icon: "php" },
        { name: "TypeScript", category: "Frontend", icon: "typescript" },
        { name: "n8n", category: "DevOps", icon: "n8n" },
        { name: "Tailwind", category: "Frontend", icon: "tailwind" },
    ];

    return { projects, skills };
};
